"use client";

import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { Search, HelpCircle, Terminal, Shield, Cpu, Zap } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import DigitalNightBackground from "@/components/DigitalNightBackground";
import BasicAccordion, { AccordionItem } from "@/components/ui/smoothui/basic-accordion";

interface CategorizedFaq extends AccordionItem {
  category: "core" | "privacy" | "integrations" | "performance" | "general";
  tags: string[];
}

const ALL_FAQS: CategorizedFaq[] = [
  // Core Concepts
  {
    id: "what-is-slop",
    category: "core",
    tags: ["slop", "basics", "definition", "ast"],
    title: "What exactly is 'AI slop' and how does Anti-Slop detect it?",
    content: (
      <div className="space-y-3">
        <p>
          <strong>AI slop</strong> refers to the low-quality, over-engineered boilerplate, phantom wrappers, hallucinated packages, and dead recursive logic commonly generated by large language models (Cursor Composer, Copilot, ChatGPT, Claude Code).
        </p>
        <p>
          Anti-Slop parses code into native <strong>Abstract Syntax Trees (ASTs)</strong> in real time and evaluates it against heuristic rule-trees. Rather than simple regex matching, it understands code structure, token cost, dependency validity, and cyclomatic complexity.
        </p>
        <div className="p-3 bg-[#131318] rounded-xl border border-white/5 font-mono text-xs text-terminal-green">
          $ antislop --scan --heuristic=ast-strict
        </div>
      </div>
    ),
  },
  {
    id: "vs-traditional-linters",
    category: "core",
    tags: ["eslint", "prettier", "linters", "biome"],
    title: "How is Anti-Slop different from ESLint, Biome, or Prettier?",
    content: (
      <div className="space-y-3">
        <p>
          Traditional linters like ESLint and Biome enforce <em>syntactic style</em> (semicolons, variable naming, indentation).
        </p>
        <p>
          Anti-Slop operates at a higher semantic level: it detects <strong>AI-specific anti-patterns</strong> such as hallucinated function parameters, unnecessary helper bloat, over-defensive nested try/catch blocks that mask errors, and token-heavy redundant abstractions. Anti-Slop works <em>alongside</em> your existing linters without any conflicts.
        </p>
      </div>
    ),
  },

  // Privacy & Security
  {
    id: "local-first-privacy",
    category: "privacy",
    tags: ["privacy", "offline", "security", "telemetry", "soc2"],
    title: "Does Anti-Slop send my code or telemetry to external servers?",
    content: (
      <div className="space-y-3">
        <p>
          <strong>No, never.</strong> Anti-Slop is 100% local-first.
        </p>
        <ul className="list-disc pl-5 space-y-1.5 text-foreground/85">
          <li>All AST parsing and auto-refactor rules run natively on your machine via compiled Rust/WASM binaries.</li>
          <li>Zero source code or metadata is ever transmitted over the network.</li>
          <li>Fully compliant with strict enterprise air-gapped workstations and SOC2 policies.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "enterprise-security",
    category: "privacy",
    tags: ["enterprise", "custom rules", "compliance"],
    title: "Can we define custom team rules and security policies?",
    content: (
      <div className="space-y-3">
        <p>
          Yes. You can add an <code className="text-terminal-green bg-white/5 px-1.5 py-0.5 rounded font-mono">.antisloprc.json</code> configuration file to the root of your repository to enable custom AST rule-trees, block specific deprecated library patterns, or enforce company-wide architectural boundaries.
        </p>
      </div>
    ),
  },

  // Integrations & IDEs
  {
    id: "supported-ides",
    category: "integrations",
    tags: ["vscode", "cursor", "jetbrains", "neovim", "cli"],
    title: "Which editors and AI tools are supported?",
    content: (
      <div className="space-y-3">
        <p>
          Anti-Slop integrates seamlessly across modern developer environments:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1 font-mono text-xs">
          <div className="p-2.5 bg-[#141419] rounded-lg border border-white/5 text-foreground/90 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-terminal-green" />
            VS Code & Cursor Extension
          </div>
          <div className="p-2.5 bg-[#141419] rounded-lg border border-white/5 text-foreground/90 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-terminal-green" />
            CLI Tool (macOS / Linux / Windows)
          </div>
          <div className="p-2.5 bg-[#141419] rounded-lg border border-white/5 text-foreground/90 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-terminal-green" />
            Git Pre-commit Hooks
          </div>
          <div className="p-2.5 bg-[#141419] rounded-lg border border-white/5 text-foreground/90 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-terminal-green" />
            CI / GitHub Actions Pass
          </div>
        </div>
      </div>
    ),
  },
  {
    id: "agent-workflow-compatibility",
    category: "integrations",
    tags: ["cursor composer", "claude code", "copilot", "chatgpt"],
    title: "How does it behave when Cursor Composer or Claude Code writes code?",
    content: (
      <div className="space-y-3">
        <p>
          Anti-Slop operates non-intrusively in the background. As AI agents generate files or multi-file diffs, Anti-Slop highlights slop in real time and offers 1-click AST simplifications, or auto-refactors files on save according to your project configuration.
        </p>
      </div>
    ),
  },

  // Performance & Cost
  {
    id: "token-and-cost-savings",
    category: "performance",
    tags: ["cost", "tokens", "speed", "velocity"],
    title: "How much LLM token cost and developer time does it actually save?",
    content: (
      <div className="space-y-3">
        <p>
          By stripping 65%+ of generated boilerplate:
        </p>
        <ul className="list-disc pl-5 space-y-1.5 text-foreground/85">
          <li><strong>Token Savings:</strong> Keeps codebase context small, saving up to 55% in API token billing across agent iterations.</li>
          <li><strong>Model Accuracy:</strong> Avoids context window saturation where LLMs start hallucinating or forgetting previous instructions.</li>
          <li><strong>Review Velocity:</strong> Saves reviewers 5–8 hours per week by shrinking PR diffs to essential logic.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "execution-speed",
    category: "performance",
    tags: ["speed", "latency", "rust", "wasm"],
    title: "Will Anti-Slop slow down my IDE or build pipeline?",
    content: (
      <div className="space-y-3">
        <p>
          No. The AST engine is written in Rust and compiled to native machine code and WASM. Full repository scans process over <strong>1,400 AST files per second</strong>, with per-file inline checks taking less than <strong>4 milliseconds</strong>.
        </p>
      </div>
    ),
  },

  // General & Setup
  {
    id: "getting-started",
    category: "general",
    tags: ["installation", "setup", "quickstart"],
    title: "How do I get started in under 60 seconds?",
    content: (
      <div className="space-y-3">
        <p>
          Install via the VS Code Marketplace or directly via npm / Homebrew:
        </p>
        <div className="p-3 bg-[#131318] rounded-xl border border-white/5 font-mono text-xs text-terminal-green">
          npm install -g antislop
          <br />
          antislop init
        </div>
        <p className="text-xs text-muted-foreground">
          Running <code className="text-foreground">antislop init</code> automatically configures your workspace with optimal presets.
        </p>
      </div>
    ),
  },
];

const CATEGORIES = [
  { id: "all", label: "All Questions", icon: HelpCircle },
  { id: "core", label: "Core Concepts", icon: Terminal },
  { id: "privacy", label: "Privacy & Security", icon: Shield },
  { id: "integrations", label: "IDEs & Agents", icon: Cpu },
  { id: "performance", label: "Performance & Cost", icon: Zap },
];

export default function FaqPage() {
  const [activeCategory, setActiveCategory] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState("");

  const filteredFaqs = useMemo(() => {
    return ALL_FAQS.filter((faq) => {
      const matchesCategory = activeCategory === "all" || faq.category === activeCategory;
      const q = searchQuery.toLowerCase().trim();
      if (!q) return matchesCategory;

      const matchesSearch =
        faq.title.toLowerCase().includes(q) ||
        faq.tags.some((tag) => tag.toLowerCase().includes(q));

      return matchesCategory && matchesSearch;
    });
  }, [activeCategory, searchQuery]);

  return (
    <div className="relative flex min-h-screen flex-col bg-background bg-grain selection:bg-terminal-green/30 selection:text-terminal-green overflow-hidden">
      <DigitalNightBackground />
      <Navbar />

      <main className="flex-1 z-10 relative pt-32 pb-24 px-6">
        <div className="max-w-5xl mx-auto flex flex-col items-center">
          
          {/* Breadcrumb Header */}
          <div className="w-full text-center mb-12">
            <div className="inline-flex items-center text-muted-foreground font-mono text-xs mb-3">
              ../Knowledge/FAQ_Database../
              <motion.span
                animate={{ opacity: [1, 1, 0, 0, 1] }}
                transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                className="inline-block w-1.5 h-[1em] bg-terminal-green ml-1 align-middle"
              />
            </div>
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-heading font-black text-foreground tracking-tight">
              Frequently Asked Questions
            </h1>
            <p className="text-muted-foreground text-base sm:text-lg max-w-2xl mx-auto mt-4 font-sans">
              Everything you need to know about eliminating AI slop, local-first AST analysis, and supercharging code review velocity.
            </p>
          </div>

          {/* Search Input Bar */}
          <div className="w-full max-w-2xl mb-8 relative">
            <div className="relative flex items-center">
              <Search className="w-4 h-4 text-muted-foreground absolute left-4 pointer-events-none" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by keyword (e.g. privacy, eslint, tokens, rust)..."
                className="w-full h-12 pl-11 pr-4 rounded-xl border border-white/10 bg-[#0E0E12]/80 backdrop-blur-md text-foreground placeholder:text-muted-foreground/60 text-sm font-sans focus:outline-none focus:border-terminal-green/60 focus:ring-1 focus:ring-terminal-green/60 transition-all shadow-lg"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery("")}
                  className="absolute right-4 text-xs font-mono text-muted-foreground hover:text-foreground"
                >
                  Clear
                </button>
              )}
            </div>
          </div>

          {/* Category Filter Switcher Tabs */}
          <div className="flex flex-wrap items-center justify-center gap-2 mb-10">
            {CATEGORIES.map((cat) => {
              const Icon = cat.icon;
              const isActive = activeCategory === cat.id;
              return (
                <button
                  key={cat.id}
                  onClick={() => setActiveCategory(cat.id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-mono transition-all duration-200 cursor-pointer ${
                    isActive
                      ? "bg-white/10 text-terminal-green border border-terminal-green/40 shadow-[0_0_15px_rgba(57,255,136,0.15)] font-semibold"
                      : "bg-[#0E0E12]/60 text-muted-foreground border border-white/5 hover:text-foreground hover:bg-white/5"
                  }`}
                >
                  <Icon className={`w-3.5 h-3.5 ${isActive ? "text-terminal-green" : "text-muted-foreground"}`} />
                  <span>{cat.label}</span>
                </button>
              );
            })}
          </div>

          {/* Accordion FAQ Container */}
          <div className="w-full max-w-3xl">
            {filteredFaqs.length > 0 ? (
              <BasicAccordion
                items={filteredFaqs}
                defaultExpandedIds={[filteredFaqs[0].id]}
                allowMultiple={true}
              />
            ) : (
              <div className="text-center py-16 px-6 rounded-2xl border border-white/5 bg-[#0D0D11]/60 backdrop-blur-sm">
                <HelpCircle className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
                <h3 className="font-heading font-semibold text-lg text-foreground">No questions found</h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Try searching with different terms or reset your category filter.
                </p>
                <button
                  onClick={() => {
                    setSearchQuery("");
                    setActiveCategory("all");
                  }}
                  className="mt-4 px-4 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-xs font-mono text-terminal-green transition-colors"
                >
                  Reset filters
                </button>
              </div>
            )}
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}
