import type { Module } from '@swc/core';
import type { SlopIssue } from '@anti-slop/shared';
import { visitAst, offsetToLineColumn, type LineMap } from '../ast/visitor';
import type { SlopRule } from './index';
import { randomUUID } from 'node:crypto';

/**
 * LOGIC-001: Detect nested ternary expressions.
 *
 * Flags ConditionalExpression nodes whose consequent or alternate
 * is also a ConditionalExpression — a sign of hard-to-read AI-generated logic.
 */
const nestedTernaryRule: SlopRule = {
  id: 'LOGIC-001',
  category: 'logic',
  severity: 'warning',
  description: 'Detect nested ternary expressions',

  check(ast: Module, source: string, filePath: string, lineMap: LineMap): SlopIssue[] {
    const issues: SlopIssue[] = [];
    // Track spans we've already flagged to avoid duplicate reports on deeply nested ternaries
    const flaggedSpans = new Set<number>();

    visitAst(ast, (node) => {
      if (node.type === 'ConditionalExpression') {
        const unwrap = (expr: any): any => {
          if (expr && expr.type === 'ParenthesisExpression') {
            return unwrap(expr.expression);
          }
          return expr;
        };

        const consequent = unwrap(node.consequent);
        const alternate = unwrap(node.alternate);

        const hasNestedConsequent = consequent?.type === 'ConditionalExpression';
        const hasNestedAlternate = alternate?.type === 'ConditionalExpression';

        if ((hasNestedConsequent || hasNestedAlternate) && !flaggedSpans.has(node.span.start)) {
          flaggedSpans.add(node.span.start);
          const loc = offsetToLineColumn(lineMap, node.span.start);
          const endLoc = offsetToLineColumn(lineMap, node.span.end);

          issues.push({
            id: randomUUID(),
            ruleId: 'LOGIC-001',
            category: 'logic',
            severity: 'warning',
            message: 'Nested ternary expression detected',
            explanation:
              'Nested ternary expressions reduce readability and are a common pattern in AI-generated code. Consider refactoring to if/else statements or a lookup map.',
            location: {
              file: filePath,
              line: loc.line,
              column: loc.column,
              endLine: endLoc.line,
              endColumn: endLoc.column,
            },
            remediationSuggestion:
              'Refactor nested ternary into if/else statements or extract into a named helper function.',
          });
        }
      }
    });

    return issues;
  },
};

/**
 * LOGIC-002: Detect empty catch blocks.
 *
 * Flags catch clauses with empty bodies — a sign of swallowed errors
 * commonly generated by AI that "handles" errors by ignoring them.
 */
const emptyCatchRule: SlopRule = {
  id: 'LOGIC-002',
  category: 'logic',
  severity: 'warning',
  description: 'Detect empty catch blocks',

  check(ast: Module, source: string, filePath: string, lineMap: LineMap): SlopIssue[] {
    const issues: SlopIssue[] = [];

    visitAst(ast, (node) => {
      if (node.type === 'CatchClause') {
        const body = node.body;
        if (body && body.type === 'BlockStatement' && (!body.stmts || body.stmts.length === 0)) {
          const loc = offsetToLineColumn(lineMap, node.span.start);
          const endLoc = offsetToLineColumn(lineMap, node.span.end);

          issues.push({
            id: randomUUID(),
            ruleId: 'LOGIC-002',
            category: 'logic',
            severity: 'warning',
            message: 'Empty catch block silently swallows errors',
            explanation:
              'Empty catch blocks hide errors and make debugging difficult. AI-generated code often includes catch blocks that do nothing, leading to silent failures.',
            location: {
              file: filePath,
              line: loc.line,
              column: loc.column,
              endLine: endLoc.line,
              endColumn: endLoc.column,
            },
            remediationSuggestion:
              'Add error handling logic, re-throw the error, or add a comment explaining why the error is intentionally ignored.',
          });
        }
      }
    });

    return issues;
  },
};

export const logicRules: SlopRule[] = [nestedTernaryRule, emptyCatchRule];
